### ISSUE TITLE
Bug on the dropdown fan speed button

### ISSUE THREAD

**Issue by beped** [denysdovhan/vacuum-card#352]
So, i have updated my Vacuum Card, HA and HA OS. But now the speed button is showing like that:
![image](https://user-images.githubusercontent.com/11295620/164009255-f4a88538-b024-4574-b362-1d770d86abd9.png)

Operating System
Home Assistant OS 7.6
Version
core-2022.4.5

Browser: Chrome and Firefox

**Comment by denysdovhan** [comment]
Try emptying your cache and fully reloading the page. This issue was already addressed.

**Comment by beped** [comment]
i have done that. No effect at all. The problem persists.
And yes, i have the latest version of the vacuum card btw.

**Comment by beped** [comment]
Maybe a conflict with another plugin? Theres a way to list all plugin installeds, so i can list it here?

**Comment by bafonins** [comment]
Hey, @beped ! I stumbled upon this issue as well when using Chrome. The following steps resolved this for me:
1. Open Chrome Dev tools
2. Navigate to the `Network` tab
3. Enable `Disable cache` checkbox
4. Navigate to the `Application` tab
5. Select `Storage`
6. Press `Clear site data` button

This resolved the issue for me. Hope this helps.
Note: I would suggest reverting steps 2-3 to enable HA caching as HA uses quite an aggressive caching strategy and disabling it might worsen your experience with HA.
