### ISSUE TITLE
Background color is applied twice, messing up themes with transparency

### ISSUE THREAD

**Issue by jsamr** [denysdovhan/vacuum-card#900]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

The background color XXX is applied twice:
1. At the `ha-card` level;
2. At the "preview" and "toolbar" level.

This result in inconsistent rendering when the theme has an alpha transparency for backgrounds, such as in https://github.com/basnijholt/lovelace-ios-themes:

**Steps to reproduce**

1. Use a theme with background transparency, e.g. `ios-dark-mode-dark-blue` from https://github.com/basnijholt/lovelace-ios-themes
2. Render a card, and observe the double application of the background.

To fix it, we just need to set the background from the top level `ha-card` to transparent. 

**Expected behavior**

The background should be applied once. 

**Screenshots**

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/7be13da2-2716-4bee-a7aa-8618baa6542d" />

**Versions:**

- Release: 2.10.1
- Browser: chrome
- HomeAssistant version: 2025.3.2

**Comment by clarinetJWD** [comment]
I fixed this in PR #902

**Comment by jsamr** [comment]
Still not addressed

**Comment by jsamr** [comment]
Still not fixed, waiting on https://github.com/denysdovhan/vacuum-card/pull/905

**Comment by jsamr** [comment]
Still not fixed
