### ISSUE TITLE
Off-Center Text with latest HA Update

### ISSUE THREAD

**Issue by chrico03** [denysdovhan/vacuum-card#917]
**Before submitting a bug**

[x ] I updated to the latest version available
[x ] I cleared the cache of my browser

**Describe the bug**

The latest HA update (2025.4.2) has caused the "Docked" and "Cleaning" text to be off-center (see screenshot)

**Expected behavior**
Both "Docked" and "Cleaning" to be centered

**Screenshots**
![Desktop](https://github.com/user-attachments/assets/2a2f97a6-7e11-438c-88ad-b92e3daac186)
![Mobile](https://github.com/user-attachments/assets/43660d62-0108-4e6d-9075-44796421fe41)

**Versions:**

- Release: [2.11.0]
- Browser: [Firefox and HA Mobile app on Android]
- HomeAssistant version: [2025.4.2]

**Comment by nelsonni** [comment]
The culprit is the `status-text` CSS class adds `28px` to the status:
https://github.com/denysdovhan/vacuum-card/blob/ad4c7b56fa79b7a8dd94437086d0ce202a65f4bd/src/styles.css#L180

This was fixed in PR #842, but unfortunately that PR has not been merged yet. @denysdovhan, is there anything we (as a community) can do to support getting these fixes merged?

**Comment by nelsonni** [comment]
Bump to prevent the bot from closing since the reported issue has not been merged and fixed yet.

**Comment by nicokapee** [comment]
With 2025.7 this is still an issue.

None of my tries to fix this with card-mod have succeeded.

**Comment by wesker84** [comment]
Confirm, still an issue in 2025.7.2.

**Comment by MDV85** [comment]
Same...(

**Comment by arychj** [comment]
I didn't want to fork the repo, so I hacked the fix in with card mod:
```yaml
type: custom:mod-card
card_mod:
  style:
    vacuum-card$: |
      .status-text { margin-left: 0 !important; }
card:
  type: custom:vacuum-card
  ...
```

**Comment by nicokapee** [comment]
> I didn't want to fork the repo, so I hacked the fix in with card mod:
> 
> type: custom:mod-card
> card_mod:
>   style:
>     vacuum-card$: |
>       .status-text { margin-left: 0 !important; }
> card:
>   type: custom:vacuum-card
>   ...

That worked for me. Thank you!

**Comment by chrico03** [comment]
Worked for me as well, thanks
